language: php
php:
  - 7.3
services:
  - mysql
before_install:
  - mysql -u root --password="" < tests/test.sql
before_script:
  - composer install
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_success:
  - travis_retry php vendor/bin/php-coveralls